# Generated by Django 5.1.6 on 2025-02-15 21:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_customuser_managers_alter_customuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_image', models.URLField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('Tour', 'Tour')], default='Tour', max_length=5)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AllowedIcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_icao', models.CharField(max_length=5)),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_icao', to='api.award')),
            ],
        ),
        migrations.CreateModel(
            name='AllowedAircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraft', models.CharField(choices=[('A10', 'A10'), ('A318', 'A318'), ('A319', 'A319'), ('A320', 'A320'), ('A321', 'A321'), ('A333', 'A333'), ('A339', 'A339'), ('A33F', 'A33F'), ('A346', 'A346'), ('A359', 'A359'), ('A388', 'A388'), ('BCS3', 'BCS3'), ('B712', 'B712'), ('B737', 'B737'), ('B738', 'B738'), ('B739', 'B739'), ('B742', 'B742'), ('B744', 'B744'), ('B748', 'B748'), ('B74S', 'B74S'), ('B752', 'B752'), ('B763', 'B763'), ('B772', 'B772'), ('B77F', 'B77F'), ('B77L', 'B77L'), ('B77W', 'B77W'), ('B788', 'B788'), ('B789', 'B789'), ('B78X', 'B78X'), ('CC19', 'CC19'), ('C130', 'C130'), ('C30H', 'C30H'), ('C30J', 'C30J'), ('C17', 'C17'), ('C172', 'C172'), ('C208', 'C208'), ('CL35', 'CL35'), ('CRJ2', 'CRJ2'), ('CRJ7', 'CRJ7'), ('CRJ9', 'CRJ9'), ('CRJX', 'CRJX'), ('DC10', 'DC10'), ('DC1F', 'DC1F'), ('DHD8', 'DHD8'), ('E75S', 'E75S'), ('E75L', 'E75L'), ('E190', 'E190'), ('F14', 'F14'), ('F16', 'F16'), ('F18', 'F18'), ('F22', 'F22'), ('MD11', 'MD11'), ('MD1F', 'MD1F'), ('P38', 'P38'), ('SR22', 'SR22'), ('TBM9', 'TBM9')], max_length=5)),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_aircrafts', to='api.award')),
            ],
        ),
        migrations.CreateModel(
            name='FlightLeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_airport', models.CharField(max_length=4)),
                ('to_airport', models.CharField(max_length=4)),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_legs', to='api.award')),
            ],
        ),
        migrations.CreateModel(
            name='PilotAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(blank=True, max_length=300, null=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('participants', models.ManyToManyField(blank=True, related_name='pilot_awards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PirepsFlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_icao', models.CharField(max_length=10, null=True)),
                ('flight_number', models.CharField(max_length=10)),
                ('departure_airport', models.CharField(max_length=50)),
                ('arrival_airport', models.CharField(max_length=50)),
                ('aircraft', models.CharField(choices=[('A10', 'A10'), ('A318', 'A318'), ('A319', 'A319'), ('A320', 'A320'), ('A321', 'A321'), ('A333', 'A333'), ('A339', 'A339'), ('A33F', 'A33F'), ('A346', 'A346'), ('A359', 'A359'), ('A388', 'A388'), ('BCS3', 'BCS3'), ('B712', 'B712'), ('B737', 'B737'), ('B738', 'B738'), ('B739', 'B739'), ('B742', 'B742'), ('B744', 'B744'), ('B748', 'B748'), ('B74S', 'B74S'), ('B752', 'B752'), ('B763', 'B763'), ('B772', 'B772'), ('B77F', 'B77F'), ('B77L', 'B77L'), ('B77W', 'B77W'), ('B788', 'B788'), ('B789', 'B789'), ('B78X', 'B78X'), ('CC19', 'CC19'), ('C130', 'C130'), ('C30H', 'C30H'), ('C30J', 'C30J'), ('C17', 'C17'), ('C172', 'C172'), ('C208', 'C208'), ('CL35', 'CL35'), ('CRJ2', 'CRJ2'), ('CRJ7', 'CRJ7'), ('CRJ9', 'CRJ9'), ('CRJX', 'CRJX'), ('DC10', 'DC10'), ('DC1F', 'DC1F'), ('DHD8', 'DHD8'), ('E75S', 'E75S'), ('E75L', 'E75L'), ('E190', 'E190'), ('F14', 'F14'), ('F16', 'F16'), ('F18', 'F18'), ('F22', 'F22'), ('MD11', 'MD11'), ('MD1F', 'MD1F'), ('P38', 'P38'), ('SR22', 'SR22'), ('TBM9', 'TBM9')], default='A10', max_length=50)),
                ('flight_duration', models.DurationField(blank=True, null=True)),
                ('registration_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Em análise', 'Em análise'), ('Aprovado', 'Aprovado'), ('Reprovado', 'Reprovado')], default='Em análise', max_length=20)),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField(default=0)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.award')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'award')},
            },
        ),
    ]
