# Generated by Django 5.1.6 on 2025-02-09 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='usernameIFC',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
    ]
