# Generated by Django 5.1.6 on 2025-02-16 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_pirepsflight_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pirepsflight',
            name='status',
            field=models.CharField(choices=[('Em análise', 'Em análise'), ('Aprovado', 'Aprovado'), ('Reprovado', 'Reprovado')], default='Em análise', max_length=20),
        ),
    ]
