# Generated by Django 5.1.6 on 2025-02-17 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_pirepsflight_network'),
    ]

    operations = [
        migrations.AddField(
            model_name='pirepsflight',
            name='observation',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='pirepsflight',
            name='status',
            field=models.CharField(choices=[('In Review', 'In Review'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Em análise', max_length=20),
        ),
    ]
