# Generated by Django 5.1.6 on 2025-02-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_pirepsflight_observation_alter_pirepsflight_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pirepsflight',
            name='observation',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
