# Generated by Django 5.1.6 on 2025-02-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_pirepsflight_observation'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightleg',
            name='leg_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
